name: git_touch
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.0+4

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_vector_icons: ^0.2.1
  flutter_highlight: ^0.5.0
  primer: ^0.0.2
  nanoid: ^0.0.6
  seti: ^0.2.0
  http: ^0.12.0
  intl: ^0.16.0
  url_launcher: ^5.0.2
  uni_links: ^0.1.4
  flutter_markdown: ^0.3.2
  shared_preferences: ^0.5.0
  share: ^0.6.0
  flutter_svg: ^0.13.0
  launch_review: ^2.0.0
  timeago: ^2.0.18
  provider: ^3.1.0
  filesize: ^1.0.4
  tuple: ^1.0.2
  uri: ^0.11.3
  fimber: ^0.3.2
  photo_view: ^0.7.0
  artemis: ^2.2.0
  # path: ../../github/artemis
  # git:
  #   url: git://github.com/pd4d10/artemis.git
  #   ref: patch-1
  gql_link: ^0.2.0
  fluro: ^1.5.1
  charts_flutter: ^0.8.1
  package_info: ^0.4.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  json_serializable: 3.2.3 # TODO:

# dependencies_overrides:
#   flutter_highlight:
#     path: ../pd4d10/highlight/flutter_highlight

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Fira Code
      fonts:
        - asset: fonts/FiraCode-Regular.ttf
        - asset: fonts/FiraCode-Bold.ttf
          weight: 700
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata-Regular.ttf
        - asset: fonts/Inconsolata-Bold.ttf
          weight: 700
    - family: PT Mono
      fonts:
        - asset: fonts/PTMono-Regular.ttf
    - family: Source Code Pro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf
        - asset: fonts/SourceCodePro-RegularItalic.ttf
          style: italic
        - asset: fonts/SourceCodePro-Bold.ttf
          weight: 700
        - asset: fonts/SourceCodePro-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Ubuntu Mono
      fonts:
        - asset: fonts/UbuntuMono-Regular.ttf
        - asset: fonts/UbuntuMono-RegularItalic.ttf
          style: italic
        - asset: fonts/UbuntuMono-Bold.ttf
          weight: 700
        - asset: fonts/UbuntuMono-BoldItalic.ttf
          style: italic
          weight: 700
