name: git_touch
description: A new Flutter project.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.12.3+24

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  ferry: ^0.10.2
  ferry_flutter: ^0.5.2
  file_icon: ^1.0.0
  filesize: ^2.0.1
  fimber: ^0.6.1
  fluro: ^2.0.3
  flutter_highlight: ^0.7.0
  flutter_markdown: ^0.6.2
  flutter_svg: ^0.22.0
  flutter_vector_icons: ^1.0.0
  github: ^8.1.0
  github_trending: ^1.1.0
  gql_http_link: ^0.4.0-nullsafety.1
  http: ^0.13.3
  # in_app_review: ^1.0.4
  intl: ^0.17.0
  json_annotation: ^4.0.1
  launch_review: ^3.0.1
  nanoid: ^1.0.0
  package_info: ^2.0.0
  primer: ^0.1.0
  provider: ^5.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  timeago: ^3.0.2
  tuple: ^2.0.0
  uni_links: ^0.5.1
  universal_io: ^2.0.4
  uri: ^1.0.0
  url_launcher: ^6.0.3
  webview_flutter: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  ferry_generator: ^0.4.2
  json_serializable: ^4.1.2

# dependencies_overrides:
#   flutter_highlight:
#     path: ../highlight/flutter_highlight
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Fira Code
      fonts:
        - asset: fonts/FiraCode-Regular.ttf
        - asset: fonts/FiraCode-Bold.ttf
          weight: 700
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata-Regular.ttf
        - asset: fonts/Inconsolata-Bold.ttf
          weight: 700
    - family: PT Mono
      fonts:
        - asset: fonts/PTMono-Regular.ttf
    - family: Source Code Pro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf
        - asset: fonts/SourceCodePro-RegularItalic.ttf
          style: italic
        - asset: fonts/SourceCodePro-Bold.ttf
          weight: 700
        - asset: fonts/SourceCodePro-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Ubuntu Mono
      fonts:
        - asset: fonts/UbuntuMono-Regular.ttf
        - asset: fonts/UbuntuMono-RegularItalic.ttf
          style: italic
        - asset: fonts/UbuntuMono-Bold.ttf
          weight: 700
        - asset: fonts/UbuntuMono-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Cascadia Code
      fonts:
        - asset: fonts/Cascadia.ttf
    - family: JetBrains Mono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
        - asset: fonts/JetBrainsMono-Italic.ttf
          style: italic
        - asset: fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: fonts/JetBrainsMono-Bold-Italic.ttf
          style: italic
          weight: 700
flutter_intl:
  enabled: true
